version: '3.7'

networks:
  defaultnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

volumes:
  mysql_data:
  cellsdir:
  data:

secrets:
  mysql_root_password:
    file: mysql_root_password.txt

services:
  db:
    restart: unless-stopped
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    secrets:
      - mysql_root_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      defaultnet:
        ipv4_address: 172.18.0.10

  pydio:
    restart: unless-stopped
    image: pydio/cells
    environment:
      CELLS_SITE_NO_TLS: 1
    volumes:
      - cellsdir:/var/cells
      - data:/var/cells/data
    networks:
      - defaultnet
    ports:
      - "8080:8080/tcp"
    depends_on:
      - db