[s3-bucket]
type = s3
provider = AWS
env_auth = true
region = eu-south-1
location_constraint = eu-south-1
acl = private
server_side_encryption = AES256
storage_class = DEEP_ARCHIVE
no_check_bucket = true